import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { CheckCircle2, Circle, Loader2, XCircle, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

type ItemStatus = 'pending' | 'in_progress' | 'done' | 'blocked';
type SectionId = 'setup' | 'assets' | 'review';

interface ChecklistItem {
  key: string;
  label: string;
  section: SectionId;
}

interface ItemState {
  status: ItemStatus;
  completed_at: string | null;
}

const CHECKLIST: ChecklistItem[] = [
  // Setup
  { key: 'form_submitted', label: 'Onboarding form submitted', section: 'setup' },
  { key: 'slack_channel', label: 'Slack channel created', section: 'setup' },
  { key: 'ghl_subaccount', label: 'GHL sub-account created', section: 'setup' },
  { key: 'welcome_email', label: 'Welcome email sent', section: 'setup' },
  { key: 'kickoff_scheduled', label: 'Kick-off call scheduled', section: 'setup' },
  // Assets (generated by auto-generate-onboarding)
  { key: 'ad_copy', label: 'Ad copy generated', section: 'assets' },
  { key: 'email_sequence', label: 'Email sequence generated', section: 'assets' },
  { key: 'sms_sequence', label: 'SMS sequence generated', section: 'assets' },
  { key: 'canva_creatives', label: 'Static ads (10 variants)', section: 'assets' },
  { key: 'avatar_created', label: 'Avatar created', section: 'assets' },
  { key: 'vsl_script', label: 'VSL script generated', section: 'assets' },
  // Review & Launch
  { key: 'manager_approved', label: 'Manager approved', section: 'review' },
  { key: 'meta_campaign', label: 'Meta campaign live', section: 'review' },
  { key: 'marked_active', label: 'Client marked active', section: 'review' },
];

const ASSET_KEYS_FROM_GENERATE = ['ad_copy', 'email_sequence', 'sms_sequence', 'canva_creatives', 'avatar_created', 'vsl_script'];

interface Props {
  clientId: string;
  clientName: string;
  primaryOffer?: any;
  section: SectionId;
  onMarkActive?: (id: string) => void;
}

export function OnboardingAutomationPanel({ clientId, clientName, primaryOffer, section, onMarkActive }: Props) {
  const [checklist, setChecklist] = useState<Record<string, ItemState>>({});
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [statusText, setStatusText] = useState<string>('');

  useEffect(() => { fetchChecklist(); /* eslint-disable-next-line */ }, [clientId]);

  async function fetchChecklist() {
    setLoading(true);
    const { data } = await supabase
      .from('clients')
      .select('automation_checklist')
      .eq('id', clientId)
      .maybeSingle();
    setChecklist(((data as any)?.automation_checklist?.items) || {});
    setLoading(false);
  }

  async function persist(next: Record<string, ItemState>) {
    setChecklist(next);
    const { error } = await supabase
      .from('clients')
      .update({ automation_checklist: { items: next, updated_at: new Date().toISOString() } } as any)
      .eq('id', clientId);
    if (error) toast.error(`Save failed: ${error.message}`);
  }

  async function setStatus(key: string, status: ItemStatus) {
    await persist({
      ...checklist,
      [key]: {
        status,
        completed_at: status === 'done' ? new Date().toISOString() : checklist[key]?.completed_at ?? null,
      },
    });
  }

  async function generateAllAssets() {
    if (!primaryOffer?.id) {
      toast.error('Add a primary offer first');
      return;
    }
    setGenerating(true);
    setStatusText('Starting AI asset generation…');
    const inProgress = { ...checklist };
    ASSET_KEYS_FROM_GENERATE.forEach(k => {
      inProgress[k] = { status: 'in_progress', completed_at: null };
    });
    await persist(inProgress);

    try {
      setStatusText('Generating copy, ads, avatar, VSL…');
      const { data, error } = await supabase.functions.invoke('auto-generate-onboarding', {
        body: {
          password: 'hpa1234',
          client_id: clientId,
          offer_id: primaryOffer.id,
          offer_description: primaryOffer.description,
          company_name: clientName,
          brand_colors: primaryOffer.brand_colors,
          brand_fonts: primaryOffer.brand_fonts,
          website_url: primaryOffer.website_url,
          intake_data: primaryOffer.raw_form_data || {},
        },
      });
      if (error) throw error;

      const r = data?.results || {};
      const next = { ...inProgress };
      const mark = (key: string, ok: boolean) => {
        next[key] = { status: ok ? 'done' : 'blocked', completed_at: ok ? new Date().toISOString() : null };
      };
      mark('ad_copy', !!r.ad_copy?.success);
      mark('email_sequence', !!r.emails?.success);
      mark('sms_sequence', !!r.sms?.success);
      mark('canva_creatives', (r.static_ads?.generated ?? 0) >= 5);
      mark('avatar_created', !!r.avatar?.generated);
      mark('vsl_script', !!r.vsl?.success);
      await persist(next);
      setStatusText('Done');
      toast.success('All onboarding assets generated');
    } catch (err: any) {
      toast.error(err?.message || 'Generation failed');
      const failed = { ...inProgress };
      ASSET_KEYS_FROM_GENERATE.forEach(k => {
        if (failed[k]?.status === 'in_progress') failed[k] = { status: 'blocked', completed_at: null };
      });
      await persist(failed);
      setStatusText('Failed');
    } finally {
      setGenerating(false);
    }
  }

  async function handleManagerDecision(approved: boolean) {
    await setStatus('manager_approved', approved ? 'done' : 'blocked');
    toast.success(approved ? 'Approved' : 'Changes requested');
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-6">
        <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
      </div>
    );
  }

  const items = CHECKLIST.filter(i => i.section === section);

  return (
    <div className="space-y-2">
      {section === 'assets' && (
        <div className="rounded-lg border bg-muted/20 p-3 flex items-center justify-between gap-3 mb-3">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" />
            <div className="text-xs text-muted-foreground">
              {generating ? statusText : 'Generates ad copy, emails, SMS, 10 static ads, avatar, VSL.'}
            </div>
          </div>
          <Button size="sm" onClick={generateAllAssets} disabled={generating}>
            {generating ? <Loader2 className="h-3.5 w-3.5 mr-1 animate-spin" /> : <Sparkles className="h-3.5 w-3.5 mr-1" />}
            Generate All Onboarding Assets
          </Button>
        </div>
      )}

      {items.map(item => {
        const state = checklist[item.key]?.status || 'pending';
        const Icon = state === 'done' ? CheckCircle2
          : state === 'in_progress' ? Loader2
          : state === 'blocked' ? XCircle
          : Circle;
        const isReview = item.key === 'manager_approved';

        return (
          <div
            key={item.key}
            className={cn(
              'flex items-center justify-between rounded-lg border px-3 py-2',
              state === 'done' && 'bg-green-500/5 border-green-500/30',
              state === 'blocked' && 'bg-destructive/5 border-destructive/30',
            )}
          >
            <div className="flex items-center gap-2.5 min-w-0">
              <Icon
                className={cn(
                  'h-4 w-4 shrink-0',
                  state === 'done' && 'text-green-500',
                  state === 'in_progress' && 'text-primary animate-spin',
                  state === 'blocked' && 'text-destructive',
                  state === 'pending' && 'text-muted-foreground',
                )}
              />
              <span className="text-sm truncate">{item.label}</span>
              {state === 'blocked' && <Badge variant="destructive" className="text-[10px] h-4">Blocked</Badge>}
            </div>
            <div className="flex items-center gap-1.5">
              {isReview ? (
                state === 'done' ? (
                  <Badge variant="outline" className="text-[10px]">Approved</Badge>
                ) : (
                  <>
                    <Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => handleManagerDecision(false)}>
                      Reject
                    </Button>
                    <Button size="sm" className="h-7 text-xs" onClick={() => handleManagerDecision(true)}>
                      Approve
                    </Button>
                  </>
                )
              ) : item.key === 'marked_active' && state !== 'done' ? (
                <Button
                  size="sm"
                  className="h-7 text-xs"
                  onClick={async () => {
                    await setStatus('marked_active', 'done');
                    onMarkActive?.(clientId);
                  }}
                >
                  Mark active
                </Button>
              ) : state !== 'done' && state !== 'in_progress' ? (
                <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={() => setStatus(item.key, 'done')}>
                  Mark done
                </Button>
              ) : state === 'done' ? (
                <Button size="sm" variant="ghost" className="h-7 text-xs text-muted-foreground" onClick={() => setStatus(item.key, 'pending')}>
                  Undo
                </Button>
              ) : null}
            </div>
          </div>
        );
      })}
    </div>
  );
}
