// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List clients visible to the signed-in user (id, name, status, slug).",
  inputSchema: {
    status: z.enum(["active", "paused", "archived"]).optional().describe("Filter by client status"),
    limit: z.number().int().min(1).max(200).default(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb(ctx).from("clients").select("id,name,status,slug,ghl_location_id,meta_ad_account_id").order("name");
    if (status) q = q.eq("status", status);
    const { data, error } = await q.limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-client-metrics.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_client_metrics_default = defineTool2({
  name: "get_client_metrics",
  title: "Get client source metrics",
  description: "Aggregate lead/call/funded metrics per client for an optional date range. Returns rows from get_client_source_metrics.",
  inputSchema: {
    client_id: z2.string().uuid().optional().describe("Filter to a single client id."),
    start_date: z2.string().optional().describe("ISO date (YYYY-MM-DD) inclusive."),
    end_date: z2.string().optional().describe("ISO date (YYYY-MM-DD) inclusive.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).rpc("get_client_source_metrics", {
      p_start_date: start_date ?? null,
      p_end_date: end_date ?? null
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).filter((r) => !client_id || r.client_id === client_id);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { rows }
    };
  }
});

// src/lib/mcp/tools/get-top-performers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_top_performers_default = defineTool3({
  name: "get_top_performers",
  title: "Get top-performing campaign/adset/ad",
  description: "Return the top-performing Meta campaign, ad set, and ad by attributed funded dollars for the given clients.",
  inputSchema: {
    client_ids: z3.array(z3.string().uuid()).optional().describe("Optional list of client ids to filter by. Omit for all visible clients.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_ids }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb3(ctx).rpc("get_top_performers", {
      p_client_ids: client_ids ?? null
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-leads.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_leads_default = defineTool4({
  name: "list_recent_leads",
  title: "List recent leads",
  description: "List the most recent leads for a client with basic contact and status info.",
  inputSchema: {
    client_id: z4.string().uuid().describe("Client id to fetch leads for."),
    limit: z4.number().int().min(1).max(100).default(25).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("leads").select("id,name,email,phone,status,source,utm_campaign,created_at,last_synced_at").eq("client_id", client_id).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jgwwmtuvjlmzapwqiabu";
var mcp_default = defineMcp({
  name: "hpa-reporting-mcp",
  title: "HPA Reporting",
  version: "0.1.0",
  instructions: "Tools for the HPA Reporting workspace. Read clients, aggregated source metrics, top-performing Meta campaigns/ads, and recent leads. All calls execute as the signed-in user under Row-Level Security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clients_default, get_client_metrics_default, get_top_performers_default, list_recent_leads_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
